### ISSUE TITLE
Cache files crash from raw SQL query

### ISSUE THREAD

**Issue by canersquid** [muxinc/mux-player-android#37]
Hi, 

First of all, thank you for the new 0.4.0 version, videos load much faster with cache on!

It works on my Samsung S10 test device, but when I want to show videos on my Huawei device (P40 Lite, without GAID, Android 10, EMUI 12), it gives me the crash below. The OS error changes to (OS error - 2:No such file or directory) sometimes. The issue occurs even if I call `enableSmartCache(false)`.

The issue arises from the raw SQL query: 
` private fun doReadLeastRecentFiles(db: SQLiteDatabase): List<FileRecord> {
    // rawQuery because none of the nicer query functions let you do sub-queries
    db.rawQuery(
      """
         select * from (
           select *,
             sum(${IndexSql.Files.Columns.diskSize}) over 
               (order by ${IndexSql.Files.Columns.lastAccessUnixTime} desc) 
               as ${IndexSql.Files.Derived.aggDiskSize}
           from ${IndexSql.Files.name}
         ) 
         where ${IndexSql.Files.Derived.aggDiskSize} > $maxDiskSize 
        """.trimIndent(),
      null,
    )
`
I think the issue is it cannot find "files", maybe the file hierarchy is different on Huawei phones. Or it can be a Android version issue with SQLite version. Edit: I have tested on other phones&emulators, it seems like the issue is happening on phones with Android 10 (sdk 29) and lower.

Crash log:

`

 java.io.IOException: java.util.concurrent.ExecutionException: android.database.sqlite.SQLiteException: near "(": syntax error (Sqlite code 1 SQLITE_ERROR): , while compiling: select * from (
                                                                                                      select *,
                                                                                                        sum(disk_size) over 
                                                                                                          (order by last_access desc) 
                                                                                                          as agg_disk_sz
                                                                                                      from files
                                                                                                    ) 
                                                                                                    where agg_disk_sz > 268435456, (OS error - 11:Try again)
                                                                                                    	at com.mux.player.internal.cache.CacheDatastore.awaitDbHelper(CacheDatastore.kt:408)
                                                                                                    	at com.mux.player.internal.cache.CacheDatastore.open(CacheDatastore.kt:60)
                                                                                                    	at com.mux.player.internal.cache.CacheController$onPlayerCreated$1.invokeSuspend(CacheController.kt:124)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1ebea90, Dispatchers.IO]
                                                                                                    Caused by: java.util.concurrent.ExecutionException: android.database.sqlite.SQLiteException: near "(": syntax error (Sqlite code 1 SQLITE_ERROR): , while compiling: select * from (
                                                                                                      select *,
                                                                                                        sum(disk_size) over 
                                                                                                          (order by last_access desc) 
                                                                                                          as agg_disk_sz
                                                                                                      from files
                                                                                                    ) 
                                                                                                    where agg_disk_sz > 268435456, (OS error - 11:Try again)
                                                                                                    	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
                                                                                                    	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
                                                                                                    	at com.mux.player.internal.cache.CacheDatastore.awaitDbHelper(CacheDatastore.kt:400)
                                                                                                    	... 10 more
                                                                                                    Caused by: android.database.sqlite.SQLiteException: near "(": syntax error (Sqlite code 1 SQLITE_ERROR): , while compiling: select * from (
                                                                                                      select *,
                                                                                                        sum(disk_size) over 
                                                                                                          (order by last_access desc) 
                                                                                                          as agg_disk_sz
                                                                                                      from files
                                                                                                    ) 
                                                                                                    where agg_disk_sz > 268435456, (OS error - 11:Try again)
                                                                                                    	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                                    	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1030)
                                                                                                    	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:637)
                                                                                                    	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:610)
                                                                                                    	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:66)
                                                                                                    	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                                                    	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
                                                                                                    	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1482)
                                                                                                    	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1416)
                                                                                                    	at com.mux.player.internal.cache.CacheDatastore.doReadLeastRecentFiles(CacheDatastore.kt:291)
                                                                                                    	at com.mux.player.internal.cache.CacheDatastore.doEvictByLru-IoAF18A(CacheDatastore.kt:271)
                                                                                                    	at com.mux.player.internal.cache.CacheDatastore.awaitDbHelper$doOpen(CacheDatastore.kt:387)
                                                                                                    	at com.mux.player.internal.cache.CacheDatastore.awaitDbHelper$lambda$16(CacheDatastore.kt:394)
                                                                                                    	at com.mux.player.internal.cache.CacheDatastore.$r8$lambda$nY7cg5XAShlhgxNJ4N9eQLXI3V4(Unknown Source:0)
                                                                                                    	at com.mux.player.internal.cache.CacheDatastore$$ExternalSyntheticLambda0.call(Unknown Source:2)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at com.mux.player.internal.cache.CacheDatastore.awaitDbHelper(CacheDatastore.kt:398)
                                                                                                    	... 10 more`

**Comment by andrewjl-mux** [comment]
Thanks for filing and including the API call details with the crash log! We're currently investigating and will follow up with any findings.
